name: Update HackerRank Stats

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"    # हर 6 घंटे बाद
  push:
    branches: [ main ]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run HackerRank Scraper
        run: node .hackerrank/fetch.js

      - name: Update README.md
        run: |
          CONTENT=$(cat HACKERRANK_STATS.md)

          sed -i "/<!--HACKERRANK-STATS-START-->/, /<!--HACKERRANK-STATS-END-->/c\
<!--HACKERRANK-STATS-START-->\n$CONTENT\n<!--HACKERRANK-STATS-END-->" README.md

      - name: Commit changes
        run: |
          git config --global user.name "actions-user"
          git config --global user.email "actions@github.com"
          git add README.md HACKERRANK_STATS.md
          git commit -m "Auto-update HackerRank stats card" || echo "No changes"
          git push
