name: Update HackerRank Badge

on:
  schedule:
    - cron: "0 */6 * * *"   # runs every 6 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Run badge script
        run: |
          node .hackerrank/fetch_badge.js

      - name: Commit changes
        run: |
          git config user.name "actions"
          git config user.email "actions@github.com"
          git add assets/hackerrank_badge_card.svg
          git commit -m "update badge card" || echo "No changes"
          git push
